version: '3'
services:
  frontend:
    image: lucasmoreno82/front-reactjs:latest
    ports:
      - "3001:3001"
  backend:
    image: lucasmoreno82/back-nodejs:v1.0.0
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
  mongodb:
    image: mongo
    ports:
      - "27017:27017"