name: Docker Image CI Front-End

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: docker login
        env: 
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run : |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Checkout the repository that contains Dockerfile
        uses: actions/checkout@v3
        with:
          repository: Lucas-Moreno/front-reactjs
          ref: main
      - name: docker build
        run: docker build . --file /home/runner/work/archi-project/archi-project/Dockerfile --tag lucasmoreno82/front-reactjs:latest
          
      - name: docker tag
        run: docker tag ${{secrets.DOCKER_USER}}/front-reactjs:latest ${{secrets.DOCKER_USER}}/front-reactjs:$(date +%s)

      - name: docker push
        run: docker push ${{secrets.DOCKER_USER}}/front-reactjs:latest