name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repository that contains Dockerfile
        uses: actions/checkout@v3
        with:
          repository: Lucas-Moreno/back-nodejs
          ref: main

      - uses: actions/checkout@v3
      - name: docker login
        env: 
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run : |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build
        run: docker build . --file /home/runner/work/archi-project/archi-project/Dockerfile --tag lucasmoreno82/back-nodejs:$(date +%s)

      - name: docker push
        run: docker push ${{secrets.DOCKER_USER}}/back-nodejs